import { View, Text, ScrollView, SafeAreaView, TouchableOpacity, FlatList, Alert, ActivityIndicator, Share } from 'react-native';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import tw from 'twrnc';
import { useCases } from '../context/CaseContext';
import * as FileSystem from 'expo-file-system';
import { useState } from 'react';

export default function CaseDetails() {
    const { id } = useLocalSearchParams();
    const { getCaseById } = useCases();
    const router = useRouter();
    const [isDownloading, setIsDownloading] = useState(false);

    const caseData = getCaseById(Array.isArray(id) ? id[0] : id);

    if (!caseData) {
        return (
            <SafeAreaView style={tw`flex-1 bg-white items-center justify-center`}>
                <Text style={tw`text-slate-500`}>Case parameters missing or not found.</Text>
                <TouchableOpacity onPress={() => router.back()} style={tw`mt-4 bg-slate-100 px-4 py-2 rounded-lg`}>
                    <Text>Go Back</Text>
                </TouchableOpacity>
            </SafeAreaView>
        );
    }

    const getTypeIcon = (type: string) => {
        switch (type) {
            case 'image': return 'image';
            case 'audio': return 'mic';
            case 'video': return 'video';
            default: return 'file-text';
        }
    };

    const getTypeColor = (type: string) => {
        switch (type) {
            case 'image': return 'text-blue-600 bg-blue-50 border-blue-100';
            case 'audio': return 'text-violet-600 bg-violet-50 border-violet-100';
            case 'video': return 'text-rose-600 bg-rose-50 border-rose-100';
            default: return 'text-amber-600 bg-amber-50 border-amber-100';
        }
    };

    const handleDownloadCase = async () => {
        if (!caseData) return;

        setIsDownloading(true);
        try {
            // Generate case file content
            const caseContent = `
NAV SAHAYAK - CASE REPORT
${'='.repeat(50)}

Case Number: ${caseData.id}
Title: ${caseData.title}
Status: ${caseData.status}
Type: ${caseData.type}
Date Filed: ${caseData.date}

${'='.repeat(50)}
DESCRIPTION
${'='.repeat(50)}
${caseData.description}

${'='.repeat(50)}
PARTIES INVOLVED
${'='.repeat(50)}
Complainant: ${(caseData as any).complainant || 'N/A'}
Accused: ${(caseData as any).accused || 'N/A'}

${'='.repeat(50)}
EVIDENCE (${caseData.evidence?.length || 0} items)
${'='.repeat(50)}
${caseData.evidence?.map((ev, idx) => `
${idx + 1}. ${ev.uri || ev.id}
   Type: ${ev.type}
   Analysis: ${ev.analysis || 'Pending'}
`).join('') || 'No evidence uploaded'}

${'='.repeat(50)}
AI ANALYSIS
${'='.repeat(50)}
${caseData.aiAnalysis || 'No AI analysis available'}

${'='.repeat(50)}
Generated by Nav Sahayak Mobile App
Date: ${new Date().toLocaleString()}
`;

            // Create file
            const fileName = `Case_${caseData.id}_${caseData.title.replace(/\s+/g, '_')}.txt`;
            const fileUri = (FileSystem as any).cacheDirectory + fileName;

            await FileSystem.writeAsStringAsync(fileUri, caseContent);

            // Share the file using React Native Share
            try {
                await Share.share({
                    message: caseContent,
                    title: `Case ${caseData.id} - ${caseData.title}`,
                });
            } catch (shareError) {
                console.log('Share cancelled or failed:', shareError);
            }
        } catch (error) {
            console.error('Download error:', error);
            Alert.alert('Download Failed', 'Could not generate case file. Please try again.');
        } finally {
            setIsDownloading(false);
        }
    };

    return (
        <SafeAreaView style={tw`flex-1 bg-slate-50`}>
            <Stack.Screen options={{ headerShown: false }} />

            {/* New Integrated Header */}
            <View style={tw`bg-white border-b border-slate-100 pt-2 pb-4 px-6 shadow-sm z-10`}>
                <View style={tw`flex-row items-center justify-between mb-4`}>
                    <TouchableOpacity onPress={() => router.back()} style={tw`w-10 h-10 rounded-full bg-slate-50 items-center justify-center border border-slate-100`}>
                        <Feather name="arrow-left" size={20} color="#0f172a" />
                    </TouchableOpacity>
                    <View style={tw`flex-row items-center gap-2`}>
                        <TouchableOpacity
                            onPress={handleDownloadCase}
                            disabled={isDownloading}
                            style={tw`w-10 h-10 rounded-full bg-emerald-50 items-center justify-center border border-emerald-200`}
                        >
                            {isDownloading ? (
                                <ActivityIndicator size="small" color="#10b981" />
                            ) : (
                                <Feather name="download" size={20} color="#10b981" />
                            )}
                        </TouchableOpacity>
                        <View style={tw`bg-indigo-50 px-3 py-1 rounded-full border border-indigo-100`}>
                            <Text style={tw`text-indigo-700 text-xs font-bold uppercase`}>{caseData.status}</Text>
                        </View>
                    </View>
                </View>

                <View>
                    <Text style={tw`text-slate-400 text-xs font-bold uppercase tracking-widest mb-1`}>Case No. {caseData.id}</Text>
                    <Text style={tw`text-slate-900 text-3xl font-extrabold tracking-tight leading-8`}>{caseData.title}</Text>
                </View>
            </View>

            <ScrollView contentContainerStyle={tw`p-6 gap-6 pb-32`}>

                {/* AI Executive Summary Card */}
                {caseData.aiAnalysis ? (
                    <View style={tw`bg-white p-6 rounded-[24px] border border-indigo-100 shadow-lg shadow-indigo-100/40`}>
                        <View style={tw`flex-row items-center justify-between mb-4`}>
                            <View style={tw`flex-row items-center gap-3`}>
                                <View style={tw`w-10 h-10 rounded-xl bg-indigo-50 items-center justify-center border border-indigo-100`}>
                                    <Feather name="cpu" size={20} color="#4f46e5" />
                                </View>
                                <Text style={tw`text-indigo-950 font-bold text-lg`}>AI Analysis</Text>
                            </View>
                            <View style={tw`bg-emerald-50 px-2 py-1 rounded-md border border-emerald-100`}>
                                <Text style={tw`text-emerald-700 text-[10px] font-bold uppercase`}>Live Update</Text>
                            </View>
                        </View>
                        <Text style={tw`text-slate-600 text-base leading-relaxed`}>
                            {caseData.aiAnalysis.summary || "No summary available."}
                        </Text>
                    </View>
                ) : (
                    <View style={tw`bg-white p-6 rounded-[24px] border border-slate-100 dashed border-2 items-center justify-center py-10`}>
                        <Feather name="cpu" size={32} color="#cbd5e1" style={tw`mb-3`} />
                        <Text style={tw`text-slate-400 font-bold`}>Waiting for AI Analysis...</Text>
                    </View>
                )}

                {/* Evidence Section (New!) */}
                <View>
                    <View style={tw`flex-row items-center justify-between mb-4 ml-1`}>
                        <Text style={tw`text-slate-900 font-bold text-lg`}>Case Evidence</Text>
                        <TouchableOpacity onPress={() => router.push({ pathname: '/evidence/[id]', params: { id: caseData.id } })}>
                            <Text style={tw`text-indigo-600 text-xs font-bold`}>Manage</Text>
                        </TouchableOpacity>
                    </View>

                    {caseData.evidence && caseData.evidence.length > 0 ? (
                        <View style={tw`gap-3`}>
                            {caseData.evidence.map((item, index) => (
                                <TouchableOpacity
                                    key={index}
                                    onPress={() => item.analysis && router.push({ pathname: '/evidence/detail', params: { caseId: caseData.id, evidenceId: item.id } })}
                                    style={tw`bg-white p-4 rounded-2xl border border-slate-100 shadow-sm flex-row items-center gap-4`}
                                >
                                    <View style={tw`w-10 h-10 rounded-xl items-center justify-center border ${getTypeColor(item.type)}`}>
                                        <Feather name={getTypeIcon(item.type) as any} size={18} style={tw`${getTypeColor(item.type).split(' ')[0]}`} />
                                    </View>
                                    <View style={tw`flex-1`}>
                                        <Text style={tw`text-slate-900 font-bold text-sm mb-0.5`}>{item.title}</Text>
                                        <Text style={tw`text-slate-400 text-[10px] font-bold uppercase`}>{item.status}</Text>
                                    </View>
                                    <Feather name="chevron-right" size={16} color="#cbd5e1" />
                                </TouchableOpacity>
                            ))}
                        </View>
                    ) : (
                        <View style={tw`bg-slate-50 p-6 rounded-2xl border border-slate-100 items-center`}>
                            <Text style={tw`text-slate-400 text-sm font-medium`}>No evidence attached yet.</Text>
                        </View>
                    )}
                </View>

                {/* Chronology & Timeline */}
                {caseData.aiAnalysis && caseData.aiAnalysis.chronological_facts && (
                    <View style={tw`bg-white p-6 rounded-[24px] border border-slate-100 shadow-sm`}>
                        <Text style={tw`text-slate-900 font-bold text-lg mb-6`}>Chronology</Text>
                        <View style={tw`gap-8 pl-2 border-l-2 border-slate-100 ml-2`}>
                            {caseData.aiAnalysis.chronological_facts.map((fact: string, index: number) => (
                                <View key={index} style={tw`pl-6 relative`}>
                                    <View style={tw`absolute -left-[11px] top-1.5 w-3 h-3 rounded-full bg-white border-[3px] border-slate-300`} />
                                    <Text style={tw`text-slate-600 leading-snug text-sm font-medium`}>{fact}</Text>
                                </View>
                            ))}
                        </View>
                    </View>
                )}

                {/* Potential Charges */}
                {caseData.aiAnalysis && caseData.aiAnalysis.potential_bns_sections && (
                    <View>
                        <Text style={tw`text-slate-900 font-bold text-lg mb-4 ml-1`}>Legal Sections</Text>
                        <View style={tw`flex-row flex-wrap gap-2`}>
                            {caseData.aiAnalysis.potential_bns_sections.map((section: string, index: number) => (
                                <View key={index} style={tw`bg-rose-50 border border-rose-100 px-3 py-2 rounded-xl flex-row items-center gap-2`}>
                                    <Feather name="alert-circle" size={14} color="#e11d48" />
                                    <Text style={tw`text-rose-900 font-bold text-xs`}>{section}</Text>
                                </View>
                            ))}
                        </View>
                    </View>
                )}

                {/* Original Description */}
                <View style={tw`bg-slate-100 p-6 rounded-[24px]`}>
                    <Text style={tw`text-slate-400 font-bold text-xs uppercase tracking-widest mb-2`}>Original Report</Text>
                    <Text style={tw`text-slate-600 italic leading-relaxed text-sm`}>{caseData.description}</Text>
                </View>

            </ScrollView>
        </SafeAreaView>
    );
}
